"""test_math_reference.py — validate the options math against INDEPENDENT
ground truth, not against itself.

WHY THIS EXISTS
test_math_contract.py is thorough about self-consistency: metrics,
option_reprice and backtest all reproduce the same fixtures, put-call parity
holds, units are right. But every one of those checks would still pass if all
three modules shared the SAME wrong formula, because the fixtures are
generated by the very code under test. Nothing pinned the numbers to an
outside reference.

This file does that, three ways that do not reuse the analytic formulas:

  1. A published textbook case (Hull, *Options, Futures and Other
     Derivatives* — S=42, K=40, r=10%, sigma=20%, T=0.5 -> call 4.76,
     put 0.81). An outside number nobody here can accidentally "fix".
  2. Monte Carlo. Prices by simulating terminal prices under the
     risk-neutral measure and discounting — a completely different
     algorithm. If the closed form (especially the dividend term, which
     production only started supplying in v3.86) is wrong, MC disagrees.
  3. Finite differences. Bumps an input and re-prices, so delta, gamma,
     vega and theta are checked against the DEFINITION of the derivative
     rather than against the hand-derived formula. A sign slip or a missing
     e^{-qT} shows up immediately.

Deterministic: the Monte Carlo uses a fixed seed, so this cannot flake.
"""
from __future__ import annotations

import math
import random
import unittest

import metrics as M


def mc_price(S, K, T, sigma, side, r, q, paths=400_000, seed=20260812):
    """Monte Carlo price under risk-neutral drift (r - q). Independent of the
    closed form: only the lognormal terminal distribution is assumed."""
    rng = random.Random(seed)
    drift = (r - q - 0.5 * sigma * sigma) * T
    vol = sigma * math.sqrt(T)
    total = 0.0
    for _ in range(paths):
        z = rng.gauss(0.0, 1.0)
        ST = S * math.exp(drift + vol * z)
        total += max(ST - K, 0.0) if side == "call" else max(K - ST, 0.0)
    return math.exp(-r * T) * total / paths


class TestPublishedReference(unittest.TestCase):
    """Hull's worked example. If this drifts, the pricer is wrong — the
    number comes from outside this repository."""

    def test_hull_european_call_and_put(self):
        S, K, T, sigma, r = 42.0, 40.0, 0.5, 0.20, 0.10
        call = M._bs_price(S, K, T, sigma, "call", r=r, q=0.0)
        put = M._bs_price(S, K, T, sigma, "put", r=r, q=0.0)
        self.assertAlmostEqual(call, 4.76, places=2)
        self.assertAlmostEqual(put, 0.81, places=2)

    def test_zero_vol_is_discounted_intrinsic(self):
        """With no vol the option is worth its forward intrinsic, discounted.
        Closed form under a limit, so it needs no simulation."""
        S, K, T, r, q = 100.0, 90.0, 1.0, 0.05, 0.03
        want = max(S * math.exp(-q * T) - K * math.exp(-r * T), 0.0)
        got = M._bs_price(S, K, T, 1e-9, "call", r=r, q=q)
        self.assertAlmostEqual(got, want, places=4)

    def test_deep_itm_call_delta_approaches_exp_minus_qT(self):
        """A deep ITM call is a forward on the stock: delta -> e^{-qT}, NOT
        1.0. This is precisely the dividend term production was missing."""
        T, q = 1.0, 0.04
        d = M._bs_delta(1000.0, 1.0, T, 0.10, "call", r=0.04, q=q)
        self.assertAlmostEqual(d, math.exp(-q * T), places=4)


class TestMonteCarloAgreement(unittest.TestCase):
    """A different algorithm entirely. Tolerances are set by the simulation's
    own standard error, not chosen to make the test pass."""

    def test_call_and_put_with_dividends(self):
        S, K, T, sigma, r, q = 100.0, 105.0, 0.75, 0.28, 0.04, 0.03
        for side in ("call", "put"):
            analytic = M._bs_price(S, K, T, sigma, side, r=r, q=q)
            simulated = mc_price(S, K, T, sigma, side, r, q)
            self.assertAlmostEqual(
                analytic, simulated, delta=0.05,
                msg=f"{side}: closed form {analytic:.4f} vs Monte Carlo {simulated:.4f}")

    def test_dividend_term_actually_bites(self):
        """Guards the failure mode this suite was written for: if q were
        ignored, these two would be equal and MC would side with the
        dividend-aware price."""
        S, K, T, sigma, r = 100.0, 100.0, 1.0, 0.30, 0.04
        no_div = M._bs_price(S, K, T, sigma, "call", r=r, q=0.0)
        with_div = M._bs_price(S, K, T, sigma, "call", r=r, q=0.05)
        self.assertGreater(no_div - with_div, 1.0,
                           "a 5% dividend yield must materially cheapen a call")
        self.assertAlmostEqual(with_div, mc_price(S, K, T, sigma, "call", r, 0.05),
                               delta=0.06)


class TestGreeksByFiniteDifference(unittest.TestCase):
    """Greeks vs the DEFINITION of the derivative, so a hand-derived formula
    cannot be wrong in the same way as its own test."""

    S, K, T, sigma, r, q = 100.0, 103.0, 0.5, 0.32, 0.042, 0.021

    def _price(self, **over):
        a = dict(S=self.S, K=self.K, T=self.T, sigma=self.sigma,
                 r=self.r, q=self.q, side="call")
        a.update(over)
        return M._bs_price(a["S"], a["K"], a["T"], a["sigma"], a["side"],
                           r=a["r"], q=a["q"])

    def test_delta_matches_dPrice_dSpot(self):
        h = 0.01
        for side in ("call", "put"):
            fd = (self._price(S=self.S + h, side=side)
                  - self._price(S=self.S - h, side=side)) / (2 * h)
            analytic = M._bs_delta(self.S, self.K, self.T, self.sigma, side,
                                   r=self.r, q=self.q)
            self.assertAlmostEqual(analytic, fd, places=5, msg=f"{side} delta")

    def test_gamma_matches_second_derivative(self):
        h = 0.05
        fd = (self._price(S=self.S + h) - 2 * self._price()
              + self._price(S=self.S - h)) / (h * h)
        analytic = M._bs_gamma(self.S, self.K, self.T, self.sigma,
                               r=self.r, q=self.q)
        self.assertAlmostEqual(analytic, fd, places=5)

    def test_vega_is_per_vol_POINT(self):
        """App convention: dollars per 1 vol point, i.e. standard vega / 100.
        A test that only compared to d(price)/d(sigma) would miss the /100."""
        h = 1e-5
        per_unit = (self._price(sigma=self.sigma + h)
                    - self._price(sigma=self.sigma - h)) / (2 * h)
        analytic = M._bs_vega(self.S, self.K, self.T, self.sigma,
                              r=self.r, q=self.q)
        self.assertAlmostEqual(analytic, per_unit / 100.0, places=5)

    def test_theta_is_per_CALENDAR_DAY(self):
        """App convention: annual theta / 365, and negative for long options."""
        h = 1e-5
        for side in ("call", "put"):
            per_year = -(self._price(T=self.T + h, side=side)
                         - self._price(T=self.T - h, side=side)) / (2 * h)
            analytic = M._bs_theta(self.S, self.K, self.T, self.sigma, side,
                                   r=self.r, q=self.q)
            self.assertAlmostEqual(analytic, per_year / 365.0, places=5,
                                   msg=f"{side} theta")
            self.assertLess(analytic, 0.0, f"long {side} must decay")


class TestProductionSuppliesRealInputs(unittest.TestCase):
    """The formulas being right is only half of it — production has to feed
    them the real rate and dividend yield. Before v3.86 every fallback greek
    call site took the library defaults (r=0.045, q=0.0), so on income names
    the strike labelled "0.20 delta" was really 0.187 (JPM) or 0.168 (VZ).
    These assertions keep those call sites honest.
    """

    # Base positional arity before r/q: delta and theta take a side, the
    # other two do not.
    BASE_ARGS = {"delta": 5, "theta": 5, "gamma": 4, "vega": 4}

    def test_no_greek_call_site_relies_on_default_rate_or_dividend(self):
        import re
        with open("options_dashboard.py", encoding="utf-8") as fh:
            src = fh.read()
        bare = []
        for m in re.finditer(r"_bs_(?P<g>delta|theta|gamma|vega)\((?P<a>[^()]*)\)", src):
            call, args = m.group(0), m.group("a")
            if "r=" in call or "q=" in call:
                continue                       # supplied by keyword
            # ...or positionally, which is equally fine.
            if len([a for a in args.split(",") if a.strip()]) > self.BASE_ARGS[m.group("g")]:
                continue
            bare.append(call)
        self.assertEqual(
            bare, [],
            "these greek call sites still take the library defaults "
            "(r=0.045, q=0.0) instead of the live rate and dividend yield "
            f"the app already knows: {bare}")

    def test_dividend_lookup_never_blocks_and_rejects_bad_data(self):
        import options_dashboard as od
        # Cold cache must return 0.0 immediately rather than fetching: this
        # runs inside the option-chain hot path.
        od._INFO_CACHE.pop("ZZTESTZZ", None)
        self.assertEqual(od._dividend_yield_cached("ZZTESTZZ"), 0.0)
        import time as _t
        od._INFO_CACHE["ZZTESTZZ"] = (_t.time(), {"dividendRate": 2.0,
                                                  "currentPrice": 100.0})
        self.assertAlmostEqual(od._dividend_yield_cached("ZZTESTZZ"), 0.02)
        # The yfinance format flip that once read 0.35% as 35% must not reach
        # the pricer as a 3500% yield.
        od._INFO_CACHE["ZZTESTZZ"] = (_t.time(), {"dividendRate": 3500.0,
                                                  "currentPrice": 100.0})
        self.assertEqual(od._dividend_yield_cached("ZZTESTZZ"), 0.0)
        od._INFO_CACHE.pop("ZZTESTZZ", None)


if __name__ == "__main__":
    unittest.main()
