// test_strategy_fixtures.js (v3.64) — fixture-matches the JS payoff engine
// (strategies.jsx → strategies.js, window.OptionStrats) against the canonical
// server-side Black-Scholes in metrics.py via the SAME fixture file that
// test_math_contract.py enforces (fixtures/options_math.json, generated by
// fixtures/generate_math_fixtures.py). Identical inputs must produce the
// same price in both languages within the normCdf approximation error
// (A&S 7.1.26, |err| ≤ 7.5e-8 per CDF call → sub-cent on any real price).
// The JS engine models q=0 only (no dividend leg-valuation), so dividend
// fixture rows apply to Python alone and are skipped here — by design,
// not oversight. Pure node. Run:  node test_strategy_fixtures.js
const fs = require("fs");
const path = require("path");
const vm = require("vm");

// strategies.js is a browser IIFE that attaches window.OptionStrats.
const src = fs.readFileSync(path.join(__dirname, "strategies.js"), "utf8");
const sandbox = { window: {}, console };
vm.runInNewContext(src, sandbox, { filename: "strategies.js" });
const OS = sandbox.window.OptionStrats;

let passed = 0, failed = 0; const fails = [];
function ok(name, cond) {
  if (cond) { passed++; console.log("  PASS  " + name); }
  else { failed++; fails.push(name); console.log("  FAIL  " + name); }
}

// ── 1. Engine surface ──────────────────────────────────────────────────────
ok("OptionStrats exported", !!OS && typeof OS.bsPrice === "function");
ok("strategy library present", OS.STRATEGIES && Object.keys(OS.STRATEGIES).length >= 12);

// ── 2. Fixture match against metrics.py ────────────────────────────────────
const fx = JSON.parse(fs.readFileSync(path.join(__dirname, "fixtures", "options_math.json"), "utf8"));
const cases = fx.cases.filter(c => c.q === 0);
ok("fixture file loaded (q=0 subset non-trivial)", cases.length >= 150);

let worst = 0, worstCase = null, mismatches = 0;
for (const c of cases) {
  const T = Math.max(0, c.days) / 365; // same year_fraction convention as metrics.py
  const got = OS.bsPrice(c.spot, c.strike, T, c.sigma, c.side === "call", c.r);
  const err = Math.abs(got - c.price);
  const tol = Math.max(5e-4, c.price * 1e-6); // A&S CDF error × two S/K-scaled terms
  if (err > tol) mismatches++;
  if (err > worst) { worst = err; worstCase = c; }
}
ok(`bsPrice matches metrics.py on all ${cases.length} q=0 fixtures`, mismatches === 0);
console.log(`        worst |Δprice| = ${worst.toExponential(2)}` +
  (worstCase ? ` (S=${worstCase.spot} K=${worstCase.strike} ${worstCase.days}d σ=${worstCase.sigma} ${worstCase.side})` : ""));

// ── 3. normCdf sanity vs exact values ─────────────────────────────────────
ok("normCdf(0) = 0.5", Math.abs(OS.normCdf(0) - 0.5) < 1e-7);
ok("normCdf(1.96) ≈ 0.9750", Math.abs(OS.normCdf(1.96) - 0.9750021048517795) < 1e-6);
ok("normCdf symmetry", Math.abs(OS.normCdf(0.7) + OS.normCdf(-0.7) - 1) < 1e-7);

// ── 4. Put-call parity inside the JS engine ───────────────────────────────
{
  const S = 100, K = 105, T = 30 / 365, sig = 0.35, r = 0.045;
  const c = OS.bsPrice(S, K, T, sig, true, r);
  const p = OS.bsPrice(S, K, T, sig, false, r);
  ok("JS put-call parity", Math.abs((c - p) - (S - K * Math.exp(-r * T))) < 1e-6);
}

// ── 5. Payoff identities (the numbers the payoff chart draws) ─────────────
// Long 100C bought for 2.50, at expiration.
const longCall = [{ type: "call", strike: 100, qty: 1, premium: 2.5, dte: 5, iv: 0.3 }];
ok("long call ITM P/L", Math.abs(OS.pnlAt(longCall, 110) - 7.5) < 1e-9);
ok("long call OTM P/L = -debit", Math.abs(OS.pnlAt(longCall, 90) + 2.5) < 1e-9);

// Short 100P sold for 3.00, at expiration.
const shortPut = [{ type: "put", strike: 100, qty: -1, premium: 3.0, dte: 5, iv: 0.3 }];
ok("short put OTM keeps credit", Math.abs(OS.pnlAt(shortPut, 105) - 3.0) < 1e-9);
ok("short put assigned P/L", Math.abs(OS.pnlAt(shortPut, 90) - (3.0 - 10.0)) < 1e-9);

// 95/105 short strangle for 2.00 total: break-evens 93 and 107.
const strangle = [
  { type: "put", strike: 95, qty: -1, premium: 1.0, dte: 5, iv: 0.3 },
  { type: "call", strike: 105, qty: -1, premium: 1.0, dte: 5, iv: 0.3 },
];
const bes = OS.breakEvens(OS.pnlCurve(strangle, 80, 120, 400)).map(x => +x.toFixed(2));
ok("strangle break-evens 93/107", bes.length === 2 && Math.abs(bes[0] - 93) < 0.11 && Math.abs(bes[1] - 107) < 0.11);
ok("strangle net credit 2.00", Math.abs(OS.netCredit(strangle) - 2.0) < 1e-9);

// Calendar: back-month leg is valued with BS at front expiry — must equal
// bsPrice with the remaining time, i.e. the same convention as metrics.py.
const backLeg = [{ type: "call", strike: 100, qty: 1, premium: 4.0, dte: 33, iv: 0.3 }];
{
  // evalDTE = 33 (only leg) → intrinsic; force a front leg to set eval at 5d.
  const cal = [
    { type: "call", strike: 100, qty: -1, premium: 2.0, dte: 5, iv: 0.3 },
    backLeg[0],
  ];
  const S = 102;
  const wantBack = OS.bsPrice(S, 100, 28 / 365, 0.3, true, 0.045);
  const wantFront = Math.max(S - 100, 0);
  const want = -1 * (wantFront - 2.0) + 1 * (wantBack - 4.0);
  ok("calendar back-leg uses BS with remaining T (days/365)", Math.abs(OS.pnlAt(cal, S) - want) < 1e-9);
}

// ── 6. Degenerate inputs collapse to intrinsic (same as metrics.py) ───────
ok("T=0 call intrinsic", OS.bsPrice(100, 90, 0, 0.3, true, 0.045) === 10);
ok("σ=0 put intrinsic", OS.bsPrice(100, 110, 30 / 365, 0, false, 0.045) === 10);

console.log(`\n${passed}/${passed + failed} passed, ${failed} failed`);
if (failed) { console.log("Failed: " + fails.join(", ")); process.exit(1); }
