#!/usr/bin/env python3
"""Regenerate fixtures/options_math.json from metrics.py — the canonical
Black-Scholes implementation (see the options-math contract in metrics.py).

The fixture file is the cross-language identity proof:
  • test_math_contract.py  asserts every Python module reproduces it, and
  • test_strategy_fixtures.js asserts the JS payoff engine matches it.

Run from the repo root ONLY when metrics.py intentionally changes:
    python3 fixtures/generate_math_fixtures.py
then commit the regenerated JSON alongside the metrics change.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from metrics import _bs_delta, _bs_gamma, _bs_price, _bs_theta, _bs_vega, year_fraction

# Grid chosen to cover the app's real ranges: cheap/expensive underlyings,
# ITM/ATM/OTM, 0DTE..LEAP, calm..panic vol, zero and non-zero rate/dividend.
CASES = []
for spot, strike in ((100.0, 100.0), (100.0, 90.0), (100.0, 110.0),
                     (25.0, 27.5), (480.0, 500.0), (1025.5, 980.0)):
    for days in (0.5, 3, 7, 30, 90, 365):
        for sigma in (0.15, 0.32, 0.80):
            for side in ("call", "put"):
                for r, q in ((0.045, 0.0), (0.04, 0.012)):
                    CASES.append({"spot": spot, "strike": strike, "days": days,
                                  "sigma": sigma, "side": side, "r": r, "q": q})
# Degenerate inputs — both engines must collapse to intrinsic, not NaN.
CASES += [
    {"spot": 100.0, "strike": 90.0, "days": 0, "sigma": 0.30, "side": "call", "r": 0.045, "q": 0.0},
    {"spot": 100.0, "strike": 110.0, "days": 0, "sigma": 0.30, "side": "put", "r": 0.045, "q": 0.0},
    {"spot": 100.0, "strike": 100.0, "days": 30, "sigma": 0.0, "side": "call", "r": 0.045, "q": 0.0},
]

for c in CASES:
    T = year_fraction(c["days"])
    a = (c["spot"], c["strike"], T, c["sigma"])
    c["price"] = _bs_price(*a, c["side"], r=c["r"], q=c["q"])
    c["delta"] = _bs_delta(*a, c["side"], r=c["r"], q=c["q"])
    c["gamma"] = _bs_gamma(*a, r=c["r"], q=c["q"])
    c["theta"] = _bs_theta(*a, c["side"], r=c["r"], q=c["q"])
    c["vega"] = _bs_vega(*a, r=c["r"], q=c["q"])

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "options_math.json")
with open(out, "w") as f:
    json.dump({"_comment": "Generated by fixtures/generate_math_fixtures.py from "
               "metrics.py — do not edit by hand. Conventions: T = days/365, "
               "sigma decimal, theta $/calendar-day, vega $/vol-point.",
               "cases": CASES}, f, indent=1)
print(f"wrote {out}: {len(CASES)} cases")
